spring.application.name=CentraleBancaire
server.port=8081
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Configuration JNDI pour WildFly
jboss.remote.naming.project.url=http-remoting://localhost:8083
jboss.remote.naming.username=admin
jboss.remote.naming.password=admin1r