-- Connexion à la base de données DepotsDB
SET PGPASSWORD=012906;
CREATE DATABASE "DepotsDB";
\c "DepotsDB" postgres 127.0.0.1 5432

-- Supprimer les tables existantes (si nécessaire pour repartir de zéro)
DROP TABLE IF EXISTS "Transactions" CASCADE;
DROP TABLE IF EXISTS "Flux" CASCADE;
DROP TABLE IF EXISTS "TypeTransactions" CASCADE;

-- Création de la table TypeTransactions
CREATE TABLE "TypeTransactions" (
    "IdTypeTransaction" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "Code" TEXT NOT NULL,
    "Description" TEXT NOT NULL,
    CONSTRAINT "PK_TypeTransactions" PRIMARY KEY ("IdTypeTransaction")
);

-- Création de la table Transactions
CREATE TABLE "Transactions" (
    "IdTransaction" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "Montant" DECIMAL(10,2) NOT NULL,
    "Reference" TEXT NOT NULL,
    "DateTransaction" TIMESTAMP WITH TIME ZONE NOT NULL,
    "UpdatedAt" TIMESTAMP WITH TIME ZONE,
    "IdTypeStatus" INTEGER NOT NULL,
    "IdTypeTransaction" INTEGER NOT NULL,
    CONSTRAINT "PK_Transactions" PRIMARY KEY ("IdTransaction"),
    CONSTRAINT "FK_Transactions_TypeTransactions" FOREIGN KEY ("IdTypeTransaction") REFERENCES "TypeTransactions"("IdTypeTransaction") ON DELETE CASCADE
    -- IdTypeStatus reste sans référence directe ici, géré via l'application
);

-- Création de la table Flux
CREATE TABLE "Flux" (
    "IdFlux" INTEGER GENERATED BY DEFAULT AS IDENTITY,
    "Sens" TEXT NOT NULL CHECK ("Sens" IN ('crédit', 'débit')),
    "Montant" DECIMAL(10,2) NOT NULL,
    "CreatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "IdCompte" INTEGER NOT NULL,
    "IdTransaction" INTEGER NOT NULL,
    CONSTRAINT "PK_Flux" PRIMARY KEY ("IdFlux"),
    -- IdCompte reste sans référence directe ici, géré via l'application
    CONSTRAINT "FK_Flux_Transactions" FOREIGN KEY ("IdTransaction") REFERENCES "Transactions"("IdTransaction") ON DELETE CASCADE
);

-- Création des index
CREATE INDEX "IX_Transactions_IdTypeTransaction" ON "Transactions"("IdTypeTransaction");
CREATE INDEX "IX_Transactions_IdTypeStatus" ON "Transactions"("IdTypeStatus");
CREATE INDEX "IX_Flux_IdTransaction" ON "Flux"("IdTransaction");
CREATE INDEX "IX_Flux_IdCompte" ON "Flux"("IdCompte");